### ISSUE TITLE
Gossip if_addr is not being sanitized if configured as a binary

### ISSUE THREAD

**Issue by whitejv81** [bitwalker/libcluster#12]
Using one of the provided sample configurations, the Gossip Strategy will fail to start as only the mutlicast_addr is being sanitized from binary to four element tuple.  Sample configuration:

```
config :libcluster,
  topologies: [
    gossip_example: [
      strategy: Elixir.Cluster.Strategy.Gossip,
      config: [
        port: 45892,
        if_addr: "0.0.0.0",
        multicast_addr: "230.1.1.251",
        multicast_ttl: 1]]]
```

**Comment by whitejv81** [comment]
Pull request with potential fix here:  https://github.com/bitwalker/libcluster/pull/13.  Will test this in the morning on an ongoing project.  Feedback is very welcome.

**Comment by whitejv81** [comment]
Just did a very simple test to ensure I was getting the expected log output:

```
22:40:56.772 [debug] [libcluster:gossip_example] heartbeat
iex(1)> 
22:40:56.777 [debug] [libcluster:gossip_example] received heartbeat from nonode@nohost

22:40:56.783 [warn]  [libcluster:gossip_example] unable to connect to :nonode@nohost
```

**Comment by bitwalker** [comment]
I've merged your PR, thanks! I'll get a new release published ASAP.

**Comment by bitwalker** [comment]
2.0.4 has been published to hex!
