### ISSUE TITLE
A topology per microservice?

### ISSUE THREAD

**Issue by jacobwarren** [bitwalker/libcluster#128]
I just read about Libcluster on Render, and it looks incredible, and I see how it works for replicas, but say I have a horizontally distributed application with microservices sitting in other pods in Kubernetes. To connect the main application to the microservices, would I just add multiple topologies for them to connect to each other?

If so how would I send messages to and from the different topologies? Since the IP isn't guaranteed to be the same each time a service goes up and down, I can't quite call `:rpc.call(:"servicename@127.0.0.1", :"Module", :function, [:"args"])` or `Node.spawn(:"servicename@127.0.0.1", :"Module", fun, args)`.

How would you recommend passing messages between topologies in this situation, or is this not a solution this library is focused on?

**Comment by bitwalker** [comment]
As you pointed out, you can have multiple topologies to connect nodes using different mechanisms, though where possible, it typically makes sense to try and get all those nodes talking on the same topology.

The libcluster library itself is transparent though, you don't need to send messages differently to access different topologies. Ultimately the node name you get will be `<node_name>@<ip>` regardless of what topology is used to get the IP. 

To deal with the side effects of node locations being transient - e.g. node A@192.168.0.10, restarts, and is then A@192.168.0.20 - is a different thing, and depends on your application. In general, a good solution is to use process groups, where each node that offers some service, joins the group on startup, and any process that needs to access the service uses `get_closest_pid` (or with the new `pg` module, `get_local_members` with fallback to `get_members` if no local instance is available). This also scales nicely to multiple instances of a service, and avoids encoding node names in your application where the code should really only care about finding an implementation of some service, regardless of what node it lives on (even if that node is more or less fixed at the moment, that can always change). In any case, that's the approach I generally reach for first.

Hope that answers your questions!
