### ISSUE TITLE
No SSL certificate validation on cluster API call

### ISSUE THREAD

**Issue by pzhuk** [bitwalker/libcluster#136]
HTTP client has hardcoded no-verification approach for SSL connections to cluster endpoints.

I guess, it might be on purpose - than has to be documented. Otherwise has to be considered as security issue?

https://github.com/bitwalker/libcluster/blob/1a0640f2b39adc430a121add01ab2ae0a4ee35b2/lib/strategy/kubernetes.ex#L223

**Comment by bitwalker** [comment]
This is no longer true if a `ca.crt` is present in the service account path. I'm open to further extending that to verify in more situations, but without a certificate bundle, we can't verify by default.
