### ISSUE TITLE
How to setup kubernetes's cluster domain  when cluster domain is not cluster.local?

### ISSUE THREAD

**Issue by gsmlg** [bitwalker/libcluster#137]
How to setup kubernetes's cluster domain  when cluster domain is not cluster.local ?

Cluster domain is not cluster.local, it is a public dns name

**Comment by seivan** [comment]
@gsmlg Would this be of interest https://github.com/bitwalker/libcluster/pull/115#issuecomment-574502876 ? 

In general the current implementation of SRV seem to hardcode to local. That being said, I don't think it works with latest K8, though I could be wrong. There's a pending issue that seems unresolved. 

However the [this provider](https://github.com/bitwalker/libcluster/pull/36) doesn't care as long as it can do a lookup.

**Comment by gsmlg** [comment]
Looks good

**Comment by bitwalker** [comment]
The PR that allows you to set `CLUSTER_DOMAIN` in the environment to override this behaviour has been merged to master and will be included in v3.3.0, I'd recommend giving that a shot.
