### ISSUE TITLE
Very noisy logging using gossip strategy

### ISSUE THREAD

**Issue by doughsay** [bitwalker/libcluster#16]
Is this expected?

<img width="670" alt="screen shot 2017-05-04 at 1 11 24 pm" src="https://cloud.githubusercontent.com/assets/221693/25725072/3fc4238c-30d3-11e7-8aad-b2152fd14c5b.png">

It logs output at least once a second, sometimes more.  This seems a bit overly chatty to me, and would blow up our centralized logging service...

**Comment by bitwalker** [comment]
It's definitely not expected, it should only be logging that if a connection is lost then re-established, this looks like it's just logging every time. I'll push a fix.

**Comment by bitwalker** [comment]
I just pushed a new minor release, `2.1.0` which addresses this by requiring strategies to implement a `list_nodes` function. The default strategies will all cover this for you, so you should just be able to upgrade and be good to go!

**Comment by doughsay** [comment]
Awesome! Thanks for the quick response!

**Comment by doughsay** [comment]
Sorry to bug; will you be pushing it to hex soon? :)

**Comment by bitwalker** [comment]
Done!
