### ISSUE TITLE
Gossip error with OTP-24 and libcluster 3.3.0

### ISSUE THREAD

**Issue by burmajam** [bitwalker/libcluster#160]
With updated lib old error message is gone but new one appeared:

```
[error] GenServer #PID<0.5792.0> terminating
** (stop) {:badarg, {'api_ng.c', 141}, 'Unknown cipher'}
    (crypto 5.0) :crypto.ng_crypto_one_time_nif(:aes_cbc256, <<...>>, true, :undefined)
    (libcluster 3.3.0) lib/strategy/gossip.ex:264: Cluster.Strategy.Gossip.encrypt/3
    (libcluster 3.3.0) lib/strategy/gossip.ex:227: Cluster.Strategy.Gossip.heartbeat/2
```

_Originally posted by @burmajam in https://github.com/bitwalker/libcluster/issues/158#issuecomment-841080746_

EDIT: I've tried it with elixir `1.11.4-otp-24` and erlang `24.0`

**Comment by svrdlans** [comment]
> With updated lib old error message is gone but new one appeared:
> 
> ```
> [error] GenServer #PID<0.5792.0> terminating
> ** (stop) {:badarg, {'api_ng.c', 141}, 'Unknown cipher'}
>     (crypto 5.0) :crypto.ng_crypto_one_time_nif(:aes_cbc256, <<...>>, true, :undefined)
>     (libcluster 3.3.0) lib/strategy/gossip.ex:264: Cluster.Strategy.Gossip.encrypt/3
>     (libcluster 3.3.0) lib/strategy/gossip.ex:227: Cluster.Strategy.Gossip.heartbeat/2
> ```
> 
> _Originally posted by @burmajam in [#158 (comment)](https://github.com/bitwalker/libcluster/issues/158#issuecomment-841080746)_
> 
> EDIT: I've tried it with elixir `1.11.4-otp-24` and erlang `24.0`

Here is my PR that resolves this issue, it was trivial to fix (that's why I could do it :) )
https://github.com/bitwalker/libcluster/pull/161

**Comment by Hermanverschooten** [comment]
I am running into the same issue, can this please be merged?

**Comment by bitwalker** [comment]
I've merged the PR, I'll push a new release sometime tonight.

**Comment by Hermanverschooten** [comment]
Any news?

**Comment by bogus-bill** [comment]
@bitwalker when is the release planned to be pushed please?

**Comment by MortezaHosseini** [comment]
Would it be merged any sooner? I really need this fix!

**Comment by loenze** [comment]
Since it has already been merged you could point your dependency to the latest commit as a workaround until an official release has been pushed:

```elixir
{:libcluster, git: "https://github.com/bitwalker/libcluster.git", ref: "a18a19c"}
```

**Comment by ilja** [comment]
Or @bitwalker could push a release 🙏🏼 
We would all be very grateful 😉

**Comment by DHager** [comment]
Ping.

**Comment by bitwalker** [comment]
I'll get a release published today

**Comment by sickill** [comment]
Would be lovely to have this released 🤞

**Comment by bitwalker** [comment]
On it

**Comment by bitwalker** [comment]
Done
