### ISSUE TITLE
Spam of warn messages making logs hard to read

### ISSUE THREAD

**Issue by Fibrasek** [bitwalker/libcluster#173]
The library works well, but the the excess of messages like:
```
11:28:51.496 [warn]  [libcluster:conduit] unable to connect to :"conduit@10.1.30.70"
```
Is making the logs harder and harder to read, is any way to deactivate those messages? I took a look in the source code and didn't found any option to do this.

Edit:

The debug seems to have an option to activate/deactivate, but the other ones don't seem to have such option, for example, the warn function for the Logger module: https://github.com/bitwalker/libcluster/blob/main/lib/logger.ex#L16

**Comment by bitwalker** [comment]
I'm unfortunately a bit tight on time at the moment, so I may not be able to address this in the near term; but if you were to open a PR with your recommended change, I'll make time to review it and help get it released.

**Comment by Fibrasek** [comment]
Deal!

**Comment by Fibrasek** [comment]
@bitwalker done PR #174 is there, made very quick changes, please comment if there's something that is needed to be changed :)

**Comment by bitwalker** [comment]
Thanks! I'll follow up there :)

**Comment by Fibrasek** [comment]
Details on the solution can be found on #174 comment by @bitwalker.
