### ISSUE TITLE
Tag for 3.3.1 on Github

### ISSUE THREAD

**Issue by oskarkook** [bitwalker/libcluster#175]
When I click on "View Source" in hexdocs from https://hexdocs.pm/libcluster/Cluster.Strategy.LocalEpmd.html, it redirects me to https://github.com/bitwalker/libcluster/blob/3.3.1/lib/strategy/local_epmd.ex#L1

The `3.3.1` tag is missing on Github.

**Comment by krns** [comment]
Hey, we just encountered the same problem when dependabot created a merge request with this description:

### Bumps [libcluster](https://github.com/bitwalker/libcluster) from 3.3.0 to 3.3.1.
<details>
<summary>Changelog</summary>

*Sourced from [libcluster's changelog](https://github.com/bitwalker/libcluster/blob/main/CHANGELOG.md).*

> # Changelog
> 
> ## Unreleased
> 
> - Use new cypher names
</details>
<details>
<summary>Commits</summary>

- See full diff in [compare view](https://github.com/bitwalker/libcluster/commits)
</details>

<br />

**Comment by bitwalker** [comment]
This will be fixed starting with 3.3.3
