### ISSUE TITLE
Gossip strategy fails with Erlang 25.1

### ISSUE THREAD

**Issue by SteffenDE** [bitwalker/libcluster#184]
Hi there,

I am having a strange issue updating from Erlang 25.0.4 to 25.1 (or later) using the hexpm elixir docker images. I am not sure if this is the correct place to report this issue, it could be an Erlang bug too, but I did not find anything else breaking.

### Steps to reproduce

I am using the Gossip strategy to connect nodes in a docker-compose network. This worked really well so far, but using Erlang > 25.1 makes nodes not connect any more. In debug mode, I also did not find any logs. To reproduce, you can use this repository, which is basically an empty project `mix new libcluster_gossip_issue --sup` with libcluster added: https://github.com/SteffenDE/libcluster_gossip_issue (see the README for more instructions).

Running two mix releases locally outside of docker does not work either, but I did not have the time to downgrade my Erlang version to see if it works with 25.0.4.

### Description of issue

Working base image: `hexpm/elixir:1.14.1-erlang-25.0.4-debian-bullseye-20220801-slim`
Not-working: `hexpm/elixir:1.14.1-erlang-25.1-debian-bullseye-20220801-slim`

25.1.1 also does not work.

Thanks for any advice!

**Comment by enewbury** [comment]
Checked this with OTP 25.0 and the nodes connect successfully, but confirming OTP 25.1 the nodes no longer find each other.

**Comment by bitwalker** [comment]
I'll have to investigate, hopefully get a fix out soon

**Comment by giusdp** [comment]
I'm also having this issue. We're using the gossip strategy to connect the nodes deployed as docker containers in a dev environment. 
The containers built with the elixir:1.13 base image manage to find each other, but with the elixir:1.14 image (which uses the latest otp version) they can't.

**Comment by hl** [comment]
Seems it works again with Erlang 25.2

**Comment by smaximov** [comment]
After looking at the changes in OTP 25.2, seems like erlang/otp#6476 was to blame.

**Comment by sleipnir** [comment]
I submitted a [PR](https://github.com/bitwalker/libcluster/pull/187) that fixes this in conjunction with some Gossip strategy setups. Maybe it can help.

Can you take a look at @bitwalker?

**Comment by bitwalker** [comment]
@sleipnir Merged, and v3.3.2 is published to Hex
