### ISSUE TITLE
Failed connection to Kubernetes API via HTTPS

### ISSUE THREAD

**Issue by lang100** [bitwalker/libcluster#19]
@bitwalker ,First, Thanks for the great library.
Trying to use the kubernetes strategy, but it keeps failing on the request to kubernetes with this error :
`2017-06-04T10:14:03.029535969Z 10:14:03.029 [error] [libcluster:examplephx] request to kubernetes failed!: {:failed_connect, [{:to_address, {'kubernetes.default.svc.cluster.local', 443}}, {:inet, [:inet], {:eoptions, {:undef, [{:ssl, :connect, ['kubernetes.default.svc.cluster.local', 443, [:binary, {:active, false}, {:ssl_imp, :new}, :inet, {:verify, :verify_none}], :infinity], []}, {:http_transport, :connect, 4, [file: 'http_transport.erl', line: 109]}, {:httpc_handler, :connect, 4, [file: 'httpc_handler.erl', line: 902]}, {:httpc_handler, :connect_and_send_first_request, 3, [file: 'httpc_handler.erl', line: 916]}, {:httpc_handler, :init, 1, [file: 'httpc_handler.erl', line: 243]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}}]}`

I have :
 - a secret containing the ERLANG_COOKIE, 
 - a config map from this vm.args file:

> ## Name of the node
> -name ${MY_BASENAME}@${MY_POD_IP}
> ## Cookie for distributed erlang
> -setcookie ${ERLANG_COOKIE}
> ## Enable SMP automatically based on availability
> -smp auto

 - and a replication controller running the app with three pods which is exposed to a service.

seems that the application cant connect to an http**s** site (http works)
although i have libssl-dev installed.

I'd appreciate if you can help me figure out what am i doing wrong or what am i missing.
thanks in advance!

**Comment by bitwalker** [comment]
Could you try again with `:ssl` and `:crypto` in your `applications` list in `mix.exs`? It looks like it's unable to find the `:ssl` application based on that error - so if that's the case, I'll ensure those are in `libcluster`'s applications list so you don't have to worry about it.

**Comment by lang100** [comment]
This was it! thanks!!
It will be great if u add it to `libcluster's` applications
although in elixir 1.4 the applications list should be empty and it would automatically be loaded ,(https://elixir-lang.org/blog/2017/01/05/elixir-v1-4-0-released/#Application) 
but, just for the case its not empty...

**Comment by bitwalker** [comment]
Great! Just FYI, but in 1.4, you still need to add Erlang applications, such as `crypto`, to `extra_applications`, as Mix can't otherwise know that you have a dependency on them (unless it is an application one of your dependencies depends on, as was the case here). I'll get that updated in the next release. Thanks for following up!
