### ISSUE TITLE
Sending messages across cluster

### ISSUE THREAD

**Issue by gmile** [bitwalker/libcluster#2]
Right now `libcluster` doesn't seem to be able to send messages across cluster. From what I can tell after looking at  [`:publish` implementation](https://github.com/bitwalker/libcluster/blob/master/lib/events.ex#L103), the event is only sent to subscribers, which are processes on that same node, but not nodes in cluster (correct me if I'm wrong).

I am using `epmd` strategy. The way I'm testing it is this:
1. Run nodes:
   
   ``` bash
   $ iex --sname node1@localhost --cookie test_cookie -S mix
   $ iex --sname node2@localhost --cookie test_cookie -S mix
   ```
2. Connect nodes:
   
   ``` elixir
   iex(node1@localhost)1> Cluster.Strategy.connect_nodes([:'node2@localhost'])
   iex(node2@localhost)1> Cluster.Strategy.connect_nodes([:'node1@localhost'])
   ```
3. Subscribe both shells to cluster events:
   
   ``` elixir
   iex(node1@localhost)2> Cluster.Events.subscribe(self())
   iex(node2@localhost)2> Cluster.Events.subscribe(self())
   ```
4. Publish event from within `node1`:
   
   ``` iex
   iex(node1@localhost)3> Cluster.Events.publish({:ok, "Hello, world!"})
   
   15:04:34.703 [debug] [libcluster] [events] <== {:publish, {:ok, "Hello, world!"}}
   :ok
   ```
5. Flush shell messages on both nodes:
   
   on node1:
   
   ``` elixir
   iex(node1@localhost)4> flush()
   {:ok, "Hello, world!"}
   :ok
   iex(node1@localhost)5>
   ```
   
   and on node2:
   
   ```
   iex(node2@localhost)3> flush()
   :ok
   ```

Was this done by design? If so, what is the purpose of publishing events within the same node?

At the same time `nodeup` and `nodedown` events work perfectly across the cluster.

Is there a plan to support publishing arbitrary events across cluster? If so, I'd like to work on a PR to bring this support.

**Comment by bitwalker** [comment]
I've removed `Cluster.Events` from `libcluster` as part of the 2.0 effort to bring libcluster into alignment with [firenest](https://github.com/phoenixframework/firenest). libcluster is really intended to only provide the means by which you cluster nodes, beyond that though, things like firenest will be where you go for distributed pub/sub. Currently, [swarm](https://github.com/bitwalker/swarm) can work as a distributed pub/sub library, but firenest is going to be a better solution for that when it is released.
