### ISSUE TITLE
How do you want to handle further strategies?

### ISSUE THREAD

**Issue by dschniepp** [bitwalker/libcluster#28]
As I saw in the latest pull request you are *not fan of rolling strategies into the mainline `libcluster` repo*. 

We developed an EC2 strategy for `libcluster` and would like to share it with the community but without a reference I am afraid that nobody will find it?

Btw thank you for your amazing contributions to the elixir community!

**Comment by bitwalker** [comment]
@dschniepp I'm definitely willing to put a list to third-party strategies in the readme of libcluster so it makes it easier for people to find them. To a degree though my reluctance depends on what is needed to implement/maintain it - if the EC2 strategy is able to get away with no dependencies and remain fairly minimal, like the Kubernetes strategy for example, then it's a big enough use case that I'd be ok with rolling it into libcluster. If on the other hand it requires other libraries, or is quite complex, I'd prefer to keep those in their own repo and link to them from here.

Let me know which path you'd like to take, and we can go from there!

**Comment by lpil** [comment]
Hello! Where can we find this EC2 strategy @dschniepp ? :)

**Comment by dschniepp** [comment]
@lpil you can find it on https://github.com/dschniepp/libcluster it's security group based. Further more I found https://github.com/kyleaa/libcluster_ec2 which is tag based.

**Comment by lpil** [comment]
Thank you @dschniepp 

Should we make a note of these in the README perhaps @bitwalker ?

**Comment by dschniepp** [comment]
@bitwalker the EC2 strategy needs further dependencies. Therefore I made a PR #31 with a readme addition.

**Comment by bitwalker** [comment]
Merged :)
