### ISSUE TITLE
Possibility to await first Lookup

### ISSUE THREAD

**Issue by maennchen** [bitwalker/libcluster#40]
Is it possible to await the first lookup until the application is started?

I have an application that should not get into the situation where there are name conflicts in the cluster. Because of that it is important that the worker does not start until the cluster is detected.

How can I best achieve that?

**Comment by bitwalker** [comment]
I've addressed this by making all of the strategies default to blocking during startup to attempt and make a first connection, with the exception of the gossip strategy. All strategies within libcluster moving forward will adhere to this principle.
