### ISSUE TITLE
Libcluster crash when using the `.hosts.erlang` clustering strategy

### ISSUE THREAD

**Issue by tchoutri** [bitwalker/libcluster#51]
Hi @bitwalker! I'm trying to use the `ErlangHosts` strategy but it crashes with this stacktrace:

```Elixir
20:18:28.149 [info]  Application libcluster exited: Cluster.App.start(:normal, []) returned an error: shutdown: failed to start child: Cluster.Strategy.ErlangHosts
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in Cluster.Strategy.ErlangHosts.configured_timeout/1
            (libcluster) lib/strategy/erlang_hosts.ex:47: Cluster.Strategy.ErlangHosts.configured_timeout([topology: :erlang_hosts, connect: {:net_kernel, :connect, []}, disconnect: {:net_kernel, :disconnect, []}, list_nodes: {:erlang, :nodes, [:connected]}, config: [timeout: 30000]])
            (libcluster) lib/strategy/erlang_hosts.ex:37: Cluster.Strategy.ErlangHosts.init/1
            (stdlib) gen_server.erl:365: :gen_server.init_it/2
            (stdlib) gen_server.erl:333: :gen_server.init_it/6

```

From what I can see, it could be because [configured_timeout](https://github.com/bitwalker/libcluster/blob/master/lib/strategy/erlang_hosts.ex#L47) is not called with a map like `%{opts: opts}` but with the [result of the map](https://github.com/bitwalker/libcluster/blob/master/lib/strategy/erlang_hosts.ex#L44).

Do you wish me to open a PR to fix this? :)

**Comment by bitwalker** [comment]
Thanks for reporting! I've pushed a fix to master, I'm going to be cleaning a few things up and pushing a new release today as well.

**Comment by tchoutri** [comment]
awesome! Thank you so much! It's always a pleasure to contribute :3
