### ISSUE TITLE
Refactor to allow injecting strategies outside the builtin ones. 

### ISSUE THREAD

**Issue by seivan** [bitwalker/libcluster#59]
Seems a lot of the code between the strategies could be reused between them and even used outside.
The biggest difference I see is essentially how it access a list of nodes wether its hardcoded or does a lookup. 

Could be useful to make it easier to add new strategies if you could dog food some code for the existing builtin ones.

**Comment by bitwalker** [comment]
I am planning a new major release which consolidates some of this, but it would have been a backwards incompatible change which I didn't feel was appropriate for a minor release, and I didn't want to do a series of breaking changes early in the project life until I had a better feel for what custom strategies were being implemented. With the lessons learned so far, I have a cleaner design in mind moving forward.
