### ISSUE TITLE
Any chance of a new release to hex?

### ISSUE THREAD

**Issue by sbennett33** [bitwalker/libcluster#62]
Hey!

We're running into an issue on our Kubernetes cluster running the latest release in hex (v2.3.0) that looks like it has be fixed as part of an already merged PR #38. Any chance we could get an new release in hex that contains that PR?

PS. Thanks for all your awesome work. We're actively using (or about to use) several of your packages and they've been extremely helpful.

**Comment by bitwalker** [comment]
I'll be pushing a new release today :)
