### ISSUE TITLE
Need more information on Multicast mode

### ISSUE THREAD

**Issue by shall3790** [bitwalker/libcluster#67]
Hello,

We are looking at using libcluster at our org and the network/infrastructure people need more information on how libcluster uses multicast.  Do you have a whitepaper or some docs on the library and how it uses Multicast?  Dense mode vs Sparse mode, does it use subscriptions with pruning, etc.

Thank you,

Stephen

**Comment by jmerriweather** [comment]
Dense mode vs Sparse mode is an implementation detail of multicast and greatly depends on the switches you use and the environment. Looking at the code the multicast mode sends membership join messages, so should work with either mode. Your networking specialist should know whether dense or sparse mode is appropriate for your environment, they should be able to see a multicast membership group with the multicast_addr.

**Comment by bitwalker** [comment]
@shall3790 Does that answer your question? The library uses multicast via `:gen_udp` to broadcast heartbeat messages, at which point the connection between nodes is made via TCP (using the standard Erlang distribution protocol, could be something else, albeit unlikely, if you are doing your own distribution plumbing). The details of `:gen_udp` are covered in the Erlang docs [here](http://erlang.org/doc/man/gen_udp.html). The configuration options provided to libcluster are passed through more or less untouched directly to `:gen_udp`, so the docs are most likely your best source of answers. If there is anything else I can answer, comment here and I'll reply as soon as I'm able!

**Comment by shall3790** [comment]
Yes, thank you.  We will look into the :gen_udp documentation.
