### ISSUE TITLE
Multiple topologies with same Strategy

### ISSUE THREAD

**Issue by jonzlin95** [bitwalker/libcluster#69]
Hi. I was trying to set up multiple clusters of the same nodes running the same strategy from my mix config, but but I noticed that each worker in the strategy is currently id'd using `__MODULE__`, making it so that you can only configure topology of each strategy in the configs.exs file. Unsure if this is intended and just wanted to drop a note. 

I've fallen back to some configuration hacks for the meantime.
Thanks!

**Comment by bitwalker** [comment]
This is changing in an upcoming release, as I know the current configuration is not ideal, should be out this week I hope!
