### ISSUE TITLE
Allow multiple discoveries to be started

### ISSUE THREAD

**Issue by josevalim** [bitwalker/libcluster#7]
And allow the connect/disnonect callbacks to be configured. It is important to check the result of the callbacks as returning `:ignored` means the node is not part of a network and that `false` means it cannot connect.

**Comment by josevalim** [comment]
Here we go: https://github.com/phoenixframework/firenest/blob/7a10044c2d7bcfa4d6e68a78263baaa610fbd2c3/lib/firenest/topology.ex#L55-L72

**Comment by bitwalker** [comment]
Implemented in 1b4dfe6
