### ISSUE TITLE
libcluster v2.0.0+ not compatible with v2 config

### ISSUE THREAD

**Issue by ssboisen** [bitwalker/libcluster#8]
Hi Paul,

First of all, thanks for your amazing work on many different elixir projects like Timex and exrm - all of which have been great contributions to the elixir community and which we have been very happy to work with at [Lix](https://github.com/lixhq).

Unfortunately It appears that version 2 of libcluster was put out a bit to hastily. There seem to have been a mix-up with the new way of configuring libcluster and old code remaining that uses the v1 style of config. My guess is that in your projects where you test libcluster you have remains of old v1 configuration which allow your testing to work - but with a clean v2 config it doesn't. 

The reason I say this is that I found a few different problems running version 2:

**Kubernetes strategy fails to initialize**:
When trying to fetch topology on [L38](https://github.com/bitwalker/libcluster/blob/master/lib/strategy/kubernetes.ex#L38) from opts we get a KeyError because what is actually passed as opts is a list with a keyword list as only element due to the wrapping of opts in a list on [L35](https://github.com/bitwalker/libcluster/blob/master/lib/strategy/kubernetes.ex#L35). Removing this wrapping solves the problem.

**Kubernetes strategy fails to look up _kubernetes_node_basename_ and _kubernetes_selector_**:
When trying to get the app-name and selector on [L101](https://github.com/bitwalker/libcluster/blob/master/lib/strategy/kubernetes.ex#L101) from the configuration we get warning logs on [L144](https://github.com/bitwalker/libcluster/blob/master/lib/strategy/kubernetes.ex#L144) due to app_name being nil. This is caused because even in v2 of libcluster it's trying to look up the configuration in the v1 format. A change which uses `Keyword.fetch!` to look up the app_name and selector from the config part of the state fixes this problem.

Best regards

Simon

**Comment by bitwalker** [comment]
I'll look into this ASAP. Sorry about that!

**Comment by bitwalker** [comment]
Published 2.0.2 with the fixes. Thanks for the detailed bug report!

**Comment by ssboisen** [comment]
Hi Paul,

Thanks for putting out a new version. We also discovered one more small mistake, the signature of the logger is wrong, see my commit:

https://github.com/bitwalker/libcluster/commit/47705add8b6b6f03044514a9e5a603e6032df635

Best regards

Simon
