### ISSUE TITLE
Reason for disconnecting from a leaving node on Kubernetes strategy

### ISSUE THREAD

**Issue by ejscunha** [bitwalker/libcluster#86]
Hey there, first of all thank you for this library 👍

While using the Kubernetes strategy we had some issues while trying to gracefully shutdown a node from the cluster, by trapping the `SIGTERM` signal.

When a node receives a `SIGTERM`, the node is removed from the list of pods of k8s internal API, so the Kubernetes strategy [disconnects](https://github.com/bitwalker/libcluster/blob/master/lib/strategy/kubernetes.ex#L100-L110) the node from the cluster.

Since we are using Swarm to distribute processes around the cluster, we have a problem when the node is disconnected from the cluster (sooner than we expected), since Swarm will redistribute the node processes on the rest of the cluster, while these processes are still being processed by the node. Even worse, Swarm will spawn the processes that were running in the rest of the cluster in the current node. 

To fix this we used an altered version of the Kubernetes strategy which does not disconnect from removed pods, since eventually they will disconnect by them selves eventually, but we would like to know if there is any reason for explicitly disconnecting from a removed pod and what consequences we could have by not doing it?

**Comment by bitwalker** [comment]
We could support this use case by allowing a null `disconnect_node` function, in which case disconnects are deferred until the underlying distribution identifies that the node has gone down; but generally you want to know about a pod leaving the cluster as soon as possible, rather than waiting until the heartbeats expire and the node is disconnected forcefully.

**Comment by ejscunha** [comment]
Thank you for your reply and suggestion 🙏
