### ISSUE TITLE
Release with `kubernetes_ip_lookup_mode`

### ISSUE THREAD

**Issue by miguelfteixeira** [bitwalker/libcluster#93]
Hi 👋

I would like to know if there's a plan to release a new version of `libcluster` any time soon with support for the `kubernetes_ip_lookup_mode` option.

We're relying on the `pod` mode to only tigger a disconnect call when a pod receive a `sigkill`. Otherwise we've a graceful shutdown process being handled on the pod that receive the `sigterm`.

I'm also curious to know if there's a plan to change the default value to `pod` because although I agree that `endpoints` provides a safe default during the Pod initialisation it also result on the other pods receiving a disconnect call while a pod is (potentially) being gracefully terminated.

Thanks 🙏

**Comment by bitwalker** [comment]
I'm planning to push a new release today

**Comment by miguelfteixeira** [comment]
Thanks 🙏
